### ISSUE TITLE
Intersection typo

### ISSUE THREAD

**Issue by thepelkus-too** [graysonarts/7DaysOfCoding#1]
https://github.com/graysonarts/7DaysOfCoding/blob/2e6d9ff9548909fb1f0e75020a310c980f313f60/2021-07/1-Mirror/sketches/2021.07.07-17.01.31.js#L40

Think this should be:
```
  const q = vec2.cross(sa, ba) / u;
```
based on the source material

**Comment by graysonarts** [comment]
Fixed! Thanks for catching that!
